import logging
from itertools import chain

from . import countries

LOGGER = logging.getLogger(__name__)

default_continent_code = "CCC"
default_continent_codes_set = {default_continent_code}

# fmt: off
continent_names__continent_codes = {
    "Africa"        : "AFR",
    "North America" : "NAC",  # "NAM" clashes with "Namibia"
    "Oceania"       : "OCE",
    "Antarctica"    : "ANA",  # "ANT" clashes with "Netherlands Antilles"
    "Asia"          : "ASI",
    "Europe"        : "EUR",
    "South America" : "SAC",
    "Others"        : default_continent_code,
   }

country_code__continent_codes_set = {
    "AF": {"ASI"},
    "XK": {"EUR"},
    "AL": {"EUR"},
    "AQ": {"ANA"},
    "DZ": {"AFR"},
    "AS": {"OCE"},
    "AD": {"EUR"},
    "AO": {"AFR"},
    "AG": {"NAC"},
    "AZ": {"EUR", "ASI"},
    "AR": {"SAC"},
    "AU": {"OCE"},
    "AT": {"EUR"},
    "BS": {"NAC"},
    "BH": {"ASI"},
    "BD": {"ASI"},
    "AM": {"EUR", "ASI"},
    "BB": {"NAC"},
    "BE": {"EUR"},
    "BM": {"NAC"},
    "BT": {"ASI"},
    "BO": {"SAC"},
    "BA": {"EUR"},
    "BW": {"AFR"},
    "BV": {"ANA"},
    "BR": {"SAC"},
    "BZ": {"NAC"},
    "IO": {"ASI"},
    "SB": {"OCE"},
    "VG": {"NAC"},
    "BN": {"ASI"},
    "BG": {"EUR"},
    "MM": {"ASI"},
    "BI": {"AFR"},
    "BY": {"EUR"},
    "KH": {"ASI"},
    "CM": {"AFR"},
    "CA": {"NAC"},
    "CV": {"AFR"},
    "KY": {"NAC"},
    "CF": {"AFR"},
    "LK": {"ASI"},
    "TD": {"AFR"},
    "CL": {"SAC"},
    "CN": {"ASI"},
    "TW": {"ASI"},
    "CX": {"ASI"},
    "CC": {"ASI"},
    "CO": {"SAC"},
    "KM": {"AFR"},
    "YT": {"AFR"},
    "CG": {"AFR"},
    "CD": {"AFR"},
    "CK": {"OCE"},
    "CR": {"NAC"},
    "HR": {"EUR"},
    "CU": {"NAC"},
    "CY": {"EUR", "ASI"},
    "CZ": {"EUR"},
    "BJ": {"AFR"},
    "DK": {"EUR"},
    "DM": {"NAC"},
    "DO": {"NAC"},
    "EC": {"SAC"},
    "SV": {"NAC"},
    "GQ": {"AFR"},
    "ET": {"AFR"},
    "ER": {"AFR"},
    "EE": {"EUR"},
    "FO": {"EUR"},
    "FK": {"SAC"},
    "GS": {"ANA"},
    "FJ": {"OCE"},
    "FI": {"EUR"},
    "AX": {"EUR"},
    "FR": {"EUR"},
    "GF": {"SAC"},
    "PF": {"OCE"},
    "TF": {"ANA"},
    "DJ": {"AFR"},
    "GA": {"AFR"},
    "GE": {"EUR", "ASI"},
    "GM": {"AFR"},
    "DE": {"EUR"},
    "GH": {"AFR"},
    "GI": {"EUR"},
    "KI": {"OCE"},
    "GR": {"EUR"},
    "GL": {"NAC"},
    "GD": {"NAC"},
    "GP": {"NAC"},
    "GU": {"OCE"},
    "GT": {"NAC"},
    "GN": {"AFR"},
    "GY": {"SAC"},
    "HT": {"NAC"},
    "HM": {"ANA"},
    "VA": {"EUR"},
    "HN": {"NAC"},
    "HK": {"ASI"},
    "HU": {"EUR"},
    "IS": {"EUR"},
    "IN": {"ASI"},
    "ID": {"ASI"},
    "IR": {"ASI"},
    "IQ": {"ASI"},
    "IE": {"EUR"},
    "IL": {"ASI"},
    "IT": {"EUR"},
    "CI": {"AFR"},
    "JM": {"NAC"},
    "JP": {"ASI"},
    "KZ": {"EUR", "ASI"},
    "JO": {"ASI"},
    "KE": {"AFR"},
    "KP": {"ASI"},
    "KR": {"ASI"},
    "KW": {"ASI"},
    "KG": {"ASI"},
    "LA": {"ASI"},
    "LB": {"ASI"},
    "LS": {"AFR"},
    "LV": {"EUR"},
    "LR": {"AFR"},
    "LY": {"AFR"},
    "LI": {"EUR"},
    "LT": {"EUR"},
    "LU": {"EUR"},
    "MO": {"ASI"},
    "MG": {"AFR"},
    "MW": {"AFR"},
    "MY": {"ASI"},
    "MV": {"ASI"},
    "ML": {"AFR"},
    "MT": {"EUR"},
    "MQ": {"NAC"},
    "MR": {"AFR"},
    "MU": {"AFR"},
    "MX": {"NAC"},
    "MC": {"EUR"},
    "MN": {"ASI"},
    "MD": {"EUR"},
    "ME": {"EUR"},
    "MS": {"NAC"},
    "MA": {"AFR"},
    "MZ": {"AFR"},
    "OM": {"ASI"},
    "NA": {"AFR"},
    "NR": {"OCE"},
    "NP": {"ASI"},
    "NL": {"EUR"},
    "AN": {"NAC"},
    "CW": {"NAC"},
    "AW": {"NAC"},
    "SX": {"NAC"},
    "BQ": {"NAC"},
    "NC": {"OCE"},
    "VU": {"OCE"},
    "NZ": {"OCE"},
    "NI": {"NAC"},
    "NE": {"AFR"},
    "NG": {"AFR"},
    "NU": {"OCE"},
    "NF": {"OCE"},
    "NO": {"EUR"},
    "MP": {"OCE"},
    "UM": {"OCE", "NAC"},
    "FM": {"OCE"},
    "MH": {"OCE"},
    "PW": {"OCE"},
    "PK": {"ASI"},
    "PS": {"ASI"},
    "PA": {"NAC"},
    "PG": {"OCE"},
    "PY": {"SAC"},
    "PE": {"SAC"},
    "PH": {"ASI"},
    "PN": {"OCE"},
    "PL": {"EUR"},
    "PT": {"EUR"},
    "GW": {"AFR"},
    "TL": {"ASI"},
    "PR": {"NAC"},
    "QA": {"ASI"},
    "RE": {"AFR"},
    "RO": {"EUR"},
    "RU": {"EUR", "ASI"},
    "RW": {"AFR"},
    "BL": {"NAC"},
    "SH": {"AFR"},
    "KN": {"NAC"},
    "AI": {"NAC"},
    "LC": {"NAC"},
    "MF": {"NAC"},
    "PM": {"NAC"},
    "VC": {"NAC"},
    "SM": {"EUR"},
    "ST": {"AFR"},
    "SA": {"ASI"},
    "SN": {"AFR"},
    "RS": {"EUR"},
    "SC": {"AFR"},
    "SL": {"AFR"},
    "SG": {"ASI"},
    "SK": {"EUR"},
    "VN": {"ASI"},
    "SI": {"EUR"},
    "SO": {"AFR"},
    "ZA": {"AFR"},
    "ZW": {"AFR"},
    "ES": {"EUR"},
    "SS": {"AFR"},
    "SD": {"AFR"},
    "EH": {"AFR"},
    "SR": {"SAC"},
    "SJ": {"EUR"},
    "SZ": {"AFR"},
    "SE": {"EUR"},
    "CH": {"EUR"},
    "SY": {"ASI"},
    "TJ": {"ASI"},
    "TH": {"ASI"},
    "TG": {"AFR"},
    "TK": {"OCE"},
    "TO": {"OCE"},
    "TT": {"NAC"},
    "AE": {"ASI"},
    "TN": {"AFR"},
    "TR": {"EUR", "ASI"},
    "TM": {"ASI"},
    "TC": {"NAC"},
    "TV": {"OCE"},
    "UG": {"AFR"},
    "UA": {"EUR"},
    "MK": {"EUR"},
    "EG": {"ASI" "AFR"},
    "GB": {"EUR"},
    "GG": {"EUR"},
    "JE": {"EUR"},
    "IM": {"EUR"},
    "TZ": {"AFR"},
    "US": {"NAC"},
    "VI": {"NAC"},
    "BF": {"AFR"},
    "UY": {"SAC"},
    "UZ": {"ASI"},
    "VE": {"SAC"},
    "WF": {"OCE"},
    "WS": {"OCE"},
    "YE": {"ASI"},
    "ZM": {"AFR"},
    "XD": {"ASI"},
    "XE": {"ASI"},
    "XS": {"ASI"},
    # TODO "XX - Disputed Territory" conflicts with `default_country_code`
    # "XX": {"OCE"},
    countries.default_country_code: default_continent_codes_set,
}

# fmt: on
def continent_codes_set(s):
    """
    Return a set(!) of three letter continent codes (Alpha-3) inspired
    by https://datahub.io/core/continent-codes#resource-continent-codes.
    (We could not find any relevant ISO norm)
    Defaults to {"CCC"}.

    As of now (March 2020) following countries are located on more than one
    continent:

    OCE - Oceania and NAC - North America:
        UM - United States Minor Outlying Islands

    EUR - Europe and ASI - Asia:
        RU - Russian Federation
        AM - Armenia
        GE - Georgia
        CY - Cyprus
        TR - Turkey
        KZ - Kazakhstan
        AZ - Azerbaijan

    ASI - Asia and AFR - Africa
        EG - Egypt
    """
    codes_set = country_code__continent_codes_set.get(s, default_continent_codes_set)
    if codes_set == default_continent_codes_set:
        # TODO probably would be better to return an empty list or even better
        # to create a union type `CountryCode` so that any misspelled country
        # code would lead to a type error (thrown early on, so it could be
        # dealt with early on too)
        LOGGER.warning(f"No list of continent codes found for '{s}'. Using '{codes_set}'!")
    return codes_set
